### PR TITLE
Back End Refactor

### PR DESCRIPTION
**Pull request by kibyes123**
Pa approve mga lowds

### CODE REVIEW

**Comment by sebastianyebes** [comment]
bat nag error amp

**Comment by raphaellaconsay** [comment]
### CHUYA BAI 😲😲😲😲😲😲😲

**Comment by sebastianyebes** [comment]
error nanaman tsk2

**Comment by raphaellaconsay** [comment]
magic

**Review by sebastianyebes — APPROVED** [review]
Approved

**Comment by raphaellaconsay** [comment]
**basic**

**Pull request merged**
